










"""Create RoleAllocation table

Revision ID: 7718a23fa41e
Revises: 
Create Date: 2024-09-11 11:44:48.505001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7718a23fa41e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_constraint('resource_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('resource_ibfk_2', type_='foreignkey')
        batch_op.drop_column('task_id')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('resource_allocation', schema=None) as batch_op:
        batch_op.drop_constraint('resource_allocation_ibfk_4', type_='foreignkey')
        batch_op.drop_constraint('resource_allocation_ibfk_1', type_='foreignkey')
        batch_op.drop_column('dept_id')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('role_name',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('role_name',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('resource_allocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dept_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('resource_allocation_ibfk_1', 'project', ['project_id'], ['project_id'])
        batch_op.create_foreign_key('resource_allocation_ibfk_4', 'department', ['dept_id'], ['dept_id'])

    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('task_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('resource_ibfk_2', 'project', ['project_id'], ['project_id'])
        batch_op.create_foreign_key('resource_ibfk_3', 'task', ['task_id'], ['id'])

    op.create_table('employee',
    sa.Column('employee_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('emp_name', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('gender', mysql.VARCHAR(length=6), nullable=False),
    sa.Column('qualification', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('experience', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dept_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['department.dept_id'], name='employee_ibfk_2'),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], name='employee_ibfk_3'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.resource_id'], name='employee_ibfk_1'),
    sa.PrimaryKeyConstraint('employee_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
